### PR TITLE
Add Doxygen configuration

### PR DESCRIPTION
**Pull request by coderkun**
Based on @georgkrause’s Doxygen configuration this PR introduces a configuration file for Doxygen which generates a documentation in the folder ´doc´ and docstrings for some/many/all classes and methods (see #214).

To generate the documentation, simply run

    $ doxygen Doxyfile

### CODE REVIEW

**Comment by georgkrause** [comment]
Works fine here. No we need some docstrings. Lets talk on IRC tomorrow, i would like to start on some midi stuff because i want to spend some time there.

**Comment by georgkrause** [comment]
lets merge this and add comments in new PRs

**Comment by georgkrause** [comment]
i generated it. I used a config which generates a lot of useful graphs (at least from my point of view).

- class hirarchy diagrams
- function call graphs

I used it in the first place to get the connections of the different parts of luppp without clicking through a lot if files. 

Downside is, that it takes some time to compile.

**Comment by georgkrause** [comment]
In detail, i checked:

- Use dot tool from the GraphViz package
- Generate class diagrams
- Generate collaboration diagrams
- Generate overall class hierarchy
- Generate Include dependency graphs
- Generate Included by dependency graphs
- Generate call graphs
- Generate called by graphs

**Comment by coderkun** [comment]
Baset on @georgkrause, I set the README.md file as “main” file so that we have a nice description as start page of the documentation.

Thanks for merging!

**Pull request merged**
