### PR TITLE
Scene Launch Buttons on MIDI controllers

### LINKED ISSUE #78: Output bindings for grid:launch_scene not working
I try to light up one led when scene 1 is launched. 

In order to switch on this led Launchpad need to receive note On 8 Velocity 63 (channel 1)

Note on 24 for scene 2 (same velocity)
Note on 40 for scene 3
Note on 56 for scene 4
...

When I launch a scene : the first (note on 8) led ligh up . The same led is light up for any scene.

Here is color code used by pad :

{
        "action": "grid:clip_state",
        "status": 144,
        "data": 0,
        "track": 0,
        "scene": 0,
        "state": {
            "empty": 0,
            "stopped": 46,
            "playing": 60,
            "recording": 15,
            "queueStopped": 45,
            "queuePlaying": 28,
            "queueRecording": 13
        }
    }

Here is my mapping for scene led :

{
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 8,
      "scene"  : 0
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 25,
      "scene"  : 1
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 41,
      "scene"  : 2
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 56,
      "scene"  : 3
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 72,
      "scene"  : 4
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 88,
      "scene"  : 5
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 104,
      "scene"  : 6
    },
    {
      "action" : "grid:launch_scene",
      "status" : 144,
      "data"   : 120,
      "scene"  : 7
    },

### PR DESCRIPTION
**Pull request by georgkrause**
I am not sure if this is the right fix for #78 since there is a "moving grid" mentioned, and there may be a little performance overhead because the for loop works through all midi bindings, but its working for me. 

Sorry for the commits, i wanted to make a pull reuest with just one commit, but didnt managed it. i hope it will be better next time.

### CODE REVIEW

**Comment by harryhaaren** [comment]
I had the "update all" type MIDI implemented for the APC control surface when initially writing MIDI bindings. The problem is that if there are too many MIDI messages going to the USB device, it gets traffic-jammed, and they update very slowly. I haven't tested this code yet - so I'm not sure if it suffers from it, just pointing it out from experience.

**Comment by georgkrause** [comment]
this one does no update everything, just all scene launch buttons, which is need to show the right scene on the controller. so too slow updating shouldnt be an issue, but i will test it ;)

**Comment by georgkrause** [comment]
@harryhaaren i tested again and i dont have any speed issues on updating the scenes. 

now i want to add a optional color property for the scene launch buttons, which enables sending other velocities than 127 for another color, and when this is done i think this one should be ready to merge.

**Comment by georgkrause** [comment]
@harryhaaren i am done with features now. if testing is okay and you have now complains about the code quality you can merge it...

**Comment by georgkrause** [comment]
@harryhaaren i can send a new pr without the more GUI tracks

**Comment by harryhaaren** [comment]
@georgkrause no need for a new PR, but could you explain what changes this intend to make? I can review the patches, but if you can brieftly explain the chanes that'd be nice - I'll update the title of the PR too :)

**Comment by georgkrause** [comment]
d61b5cf and 06fb0a1: updating defined scene launch buttons, behavior before was very device specific
4fd78a8: makes it possible to define other velocity values for scene launch buttons, eg setting the color on a launchpad

**Comment by harryhaaren** [comment]
To make sure I'm understanding - these changes have nothing to do with variable GUI sizes / tracks, and this PR is only for making the LaunchPad show lights based on clip state?

In order to make controllers show state, we need to send different commands: often note-on velocity maps to a color, although this is not constant between hardware implementations. This leads us to needing a flexible way of "per-controller" setting the value of each clip state, and assigning that value a MIDI velocity number.

Suggested Solution:
* Add an array `clipStateVelocityMap` to the GenericMidi class, which will be used for lookup of velocity when transmitting ClipState messages.
* A controller mapping file will have a new section for "clipStateVelocities", which maps the clip states into the velocity.

@georgkrause @geraldmwangi : does the above sound like a good solution to you both?

**Comment by georgkrause** [comment]
> To make sure I'm understanding - these changes have nothing to do with variable GUI sizes / tracks, 

yes!

>and this PR is only for making the LaunchPad show lights based on clip state?

No, its also for my apc mini, before only the first 5 scene launcher buttons worked correctly. Look at  	4fd78a8.

> In order to make controllers show state, we need to send different commands: often note-on velocity maps to a color, although the velocity->colour is not constant between hardware implementations. This leads us to needing a flexible way of "per-controller" setting the value of each clip state, and assigning that value a MIDI velocity number.

+1

> Suggested Solution:
> 
>     Add an array clipStateVelocityMap to the GenericMidi class, which will be used for lookup of velocity when transmitting ClipState messages.
>     A controller mapping file will have a new section for "clipStateVelocities", which maps the clip states into the velocity.

I think @geraldmwangi wanted to have an subclass. I dont know if its possible to load a specific subclass in dependence of the config file, but if this was easy possible its in my opinion the most flexible way. And there is no solution for the different colors of scene launch buttons on the Launchpad.

**Comment by harryhaaren** [comment]
Although a sub-class might be one way to achieve the desired behaviour, I think it over-complicates it (in an OOP way) and defeats the purpose of the "Generic" midi controller mapping. I'm open to be convinced otherwise, but the solution above seems to handle all of the requirements..

The other thing to keep in mind, is if colour shown in a value in the  `.ctlr`  file, users can script their own values *without* compiling Luppp. I know its easy for devs to do a "quick recompile" - but for a user that's not the case. Changing a value in a `.ctlr` file is reasonable enough I think though.

Opinions?

**Comment by georgkrause** [comment]
the choosen title is wrong from my point of view. this pr is just about sceneLaunch Buttons, it has nothing to do with clipstates. it was just the starting point for our discussion about using the velocity for setting a color which is not generic, as @geraldmwangi said. i would agree with that, but if you dont want the subclassing (i understand the reason) the current way is much easier and this is way i would call it better (although its "wrong" midi)

**Comment by georgkrause** [comment]
@harryhaaren i would suggest this: you merge this (i can file a clean pr if it helps). The reason is that not only the first 5 scene launch buttons on a midi controller work. but we consider this as a workaround and change the behavior of luppp for one of the next versions. right now only 5 scene launchers of my apc mini work correctly and i would like to use all 8. if you dont want this, i patch a local version on my own, no problem!

**Comment by harryhaaren** [comment]
@georgkrause : A new PR with minimal changes for the intended changes, and some note on what it should do and I'll test. Cheers

**Comment by geraldmwangi** [comment]
Hi, I'm just concerned that sending color information as 'velocity' might disturb the function of non color midi-controllers. In my opinion GenericMidi should adhere to the midi specification which does not contain color information stuff. But if you can guarantee that this PR doesn't affect non-color midi controllers then I'm fine.

But what happens if a non-color controller sends a velocity value to luppp. My nanoPad2 is used with luppp and sends notes to it which I bind to the scenes. Will luppp now start showing freaky colors since the nanoPad2 buttons also send the button pressure as velocity?

**Comment by geraldmwangi** [comment]
the last question was meant half joke/ half serious :)

**Comment by harryhaaren** [comment]
A quick review of this makes me think that it has no negative effect on controllers that do not manually set the `colour` property in the `.ctlr` file - while it does benefit those that do. @georgkrause correct?

If so, (and there's no fresh observations of otherwise ;) I'll merge in my next merge session. Cheers

**Comment by georgkrause** [comment]
@harryhaaren right! if i can manage it i will file a new pr which is clean today

**Comment by harryhaaren** [comment]
Thanks - please post comment here so we can track the changes/resolution to this issue here too. Cheers

**Comment by georgkrause** [comment]
new pr here: #144. i close this one.

**Pull request closed without merging**
