### PR TITLE
implemented the saveDirectory option

### PR DESCRIPTION
**Pull request by geraldmwangi**

### CODE REVIEW

**Comment by georgkrause** [comment]
i tested and it works. @harryhaaren from my point of view you can merge

**Comment by harryhaaren** [comment]
Hi @geraldmwangi - this doesn't apply cleanly to current head - does it depend on another patchset? I'll get to look at some PRs between Sat to Tuesday, so lets make a plan to get as much merged as we can :) Cheers, -H

**Comment by geraldmwangi** [comment]
Hi Harry Its based off rev: SHA-ID e5e57d7a7441e7a80afa85fabd5eb466ec692adb.
That's the commit I started the send-returns stuff on. You wanted independent PR's.

**Comment by harryhaaren** [comment]
@georgkrause : this is expected to work 100% (given it was an easy rebase) but if you have some time, a quick test would be appreciated. Thanks @geraldmwangi for the pull request!

**Pull request closed without merging**
