### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by georgkrause**
This enables and configures Travis CI for Luppp. It does not run tests for now since they sometimes try to open windows, which wont work. 

I still get:

```
[1/42] Generating version.hxx with a custom command.
fatal: No names found, cannot describe anything.
```

This is because we can't read the git information in Travis...

[Build Status](https://travis-ci.org/georgkrause/openAV-Luppp)

### CODE REVIEW

**Comment by harryhaaren** [comment]
Hey Georg, thanks for setting this up! I presume this is working towards getting Travis running on each PR / commit? If yes, is it ready to enable now, or is there more to do first?

**Comment by georgkrause** [comment]
Well, I am not really sure if this will run on each PR, but should run for each commit in each branch in this repository. One would need to activate this, though. But it seems like I can do this.

Honestly I am not really experienced with Travis and this is more try an error. Since its unlikely to break something I would just merge this and see what happens and fix stuff if needed. If this wont work for you, I can dig into the documentation to get how to enable PR builds.

In general to make this really useful we should have some nicely implemented Unit Tests. But for now this does not seem a good spend of time since the code is really tight coupled and therefor its hard to setup something which does not rely on the GUI...

**Comment by harryhaaren** [comment]
Ah ok, well this stuff is enabled for Ctlra repo already (https://github.com/openAVproductions/openAV-Ctlra/blob/master/.travis.yml) , so I should be able to get it to work for Luppp too :)

Yes agree that the current code is very hard to test due to tight coupling - indeed this shows that I was a novice at sw architecture when Luppp was initially created. Currently WIP OpenAV projects are a lot more modular than this version of Luppp - so the good news is that this has been addressed in more recent OpenAV software.

**Comment by georgkrause** [comment]
Absolutely no blame intended, I just wanted to justify not configuring any tests (not even the few which are available)

**Comment by harryhaaren** [comment]
Understood - and agreed. I'll try find some time over the weekend to poke the github settings to enable Travis with this PR. Thanks!

**Comment by georgkrause** [comment]
This should now create an appdir which is needed for the planned AppImage

**Comment by georgkrause** [comment]
Thanks to @probonopd, Travis also builds an AppImage and loads it into Github Releases as discussed here #237. (already tested and ready to merge)

**Comment by georgkrause** [comment]
Some information here: https://github.com/georgkrause/openAV-Luppp/pull/2

**Comment by harryhaaren** [comment]
All looks good to me folks, looks like it needs a rebase, then I'm happy for you to merge @georgkrause.

**Comment by georgkrause** [comment]
@harryhaaren Rebase is done. Should be ready to merge now. Please note the needed Travis configuration...

**Comment by harryhaaren** [comment]
Thanks folks!

**Pull request merged**
