### PR TITLE
Looper clip redesign

### PR DESCRIPTION
**Pull request by georgkrause**
This is the starting of the Redesign of the LooperClip

This is to be done:

- [x] internal buffer management
- [x] use from Stately inherited functions for saving
- [x] internal state transition with functions (easier to maintain invariants)
- [x] remove unused functions
- [x] cleanup code

If you have even more tasks, please let me know. Since the heat is slowing me down this will take some time to be completed.

### CODE REVIEW

**Comment by georgkrause** [comment]
For clarification: Saving the hole session already used the save() Method inherited from Stately. But saving a single clip is done in a different way. The aim is to unify this. This way the Clip implements one functionality to save its buffer to disk which can be used no matter if the hole session or just a single clip should be saved.

**Comment by georgkrause** [comment]
@harryhaaren I could use your advice. My initial goal was to prevent giving a pointer to the internal LC-Buffer to an instance outside of the LC-Object. The reason is that I see some problems when something outside the class changes the buffer. Anyway, I tried to refactor the code for saving the Buffer to a file. And this is where the trouble starts. In fact there are two different ways to save a Looperclip: As part of the hole session or as single file. I thought about unifying these two cases, but this seems to be not a good idea. These are two totally different aspects. Anyway, since I want to avoid giving a pointer to the buffer to something outside the object, we need a save buffer which needs to be requested by the Looperclip but generated by the GUI we have a lot of Event-Communication Overhead between GUI and DSP:

* User tells GUI to save 
* GUI tells DSP (1. Event)
* DSP decides which LCs need to be saved and call the save function
* LC requests SaveBuffer (2. Event)
* GUI generates SaveBuffer on given size and handle the pointer to LC (3. Event)
* LC copies internal Buffer to SaveBuffer and tell GUI its done (4. Event)
* GUI starts the saving process

So we need to handle 4 Events, which seems to be a big overhead to me. But I don't know how to reduce this without disturbing the realtime-safetyness of the code. So, @harryhaaren, do you have any idea? Or do you think this is already the best possible solution? 

In any case, I want to rename the Events and reduce complexity in the Events itself to make it clear what message and pointer is transported. There is one weird no_dealloc option in one event which is really confusing.

Also, please excuse me for the slow progress here. I spent a lot of time on reading code, trying to understand what is going on and try to think about the best possible solution afterwards. This is really time consuming, kind of frustrating and sadly there is no visible progress for a long time. Additionally, I am kind of stuck in trade-off decision making, so I would be happy to get some input.

**Comment by georgkrause** [comment]
I did most of the changes I wanted to apply and actually I am quite happy with the current state. Probably there are some things to improve, but they need discussion. 

1. We count the playback progress of a clip two times, in samples and in bars, this is redundant and introduces some problems. I know, I introduced this because it enables us to reset the played samples after all bars are played. But maybe there is another solution? Or is this not a problem at all? At least there is one bug: When stopping the transport, the `_barsPlayed` don't get reset. This is done in `setPlayhead()`, where we would need to set the bars to the right number. This is possible. But currently setting the playhead position is not needed so we can rename the function to `resetPlayhead()` which simply sets this to zero. Later, when we want to implement Clip retriggering or beat skipping or such fun stuff, we need to think about this again anyway.

2. Maybe its a good idea, to implement the processing of the clip insight the function, getting rid of this sample-based `getSample()` approach. But I don't know if this is a good idea as its might harder to make sure only one clip is played/processed at a time. 

All in all from my point of view the code is much more readable right now. Its easier to maintain and better encapsulated. The major stuff is done, maybe some smaller cleanups are needed. Anyway, I am looking forward to your Feedback @harryhaaren!

**Comment by harryhaaren** [comment]
Hey,

Most of the changes look fine - they're relatively intrusive changes in terms of "all of the logic is changed" - has this been extensively tested? Are you confident it is working as before?

I can do a pass over the code for code/whitespace issues etc, but the changes (at a first glance, without testing) seem ok. If you're confident the code is working correctly, I'll pull & test when I find some time (weekend hopefully)?

-H

**Comment by georgkrause** [comment]
No intensive testing was done here, I just wanted to check if this has some basic problems. Testing or feedback welcome!
I will assign the Please Merge Tag when i am happy with it.

**Comment by georgkrause** [comment]
Overall i didn't changed the functionality that much, its mostly other structure of the same instructions...

**Comment by georgkrause** [comment]
Tested:
- loading a clip
- recording a clip
- saving a clip
- launching scenes

2 Bugs found and fixed.

Testing from my side should be done, more testing welcome.

**Comment by georgkrause** [comment]
@harryhaaren I did a rebase and pushed all my local changes. My aim in general was to unify principles and to capsulate "atomic" actions. For example its not needed to manually set `_newBufferInTransit` since this is only an option when a new Buffer is requested. So this is capsulated in one function. I also bundled stuff in functions which is often used, eg updating the controllers.

For now, I would stop here. This needs pretty good review since its a critical point in Luppp. But all in all I am not really satisfied yet. Leave the fact that there is single-sample playback for now, I am also not really happy with the way a controller interacts with the Looperclip. I feel like there is to much logic outside the class. This way the LooperClip can't make sure its state is set correctly. One example: In general its a bad idea to queue the recording when the Clip already contains data, because this would overwrite the internal Buffer. So it would be nice to have something like 

```
function queueRecord() {
  if(!_loaded) {
    _queueRecord = true;
  }
}
```

But there is this feature called "XRec" in the GUI. This wants to queue the record even if there is something loaded. I am not arguing we should remove this feature, but I would prefer to tell the clip "XRec is active" and we could change the above code example to

```
function queueRecord() {
  if(!_loaded || _xrec) {
    _queueRecord = true;
  }
}
```

This way we have a clean interface of the class which also makes sure all the invariants are followed. This would probably also reduce the tight coupling a little further. 

The reason why I do not proceed here even though is the fact that I am not sure if I am right and this should be discussed. So I would like to hear your thoughts about the LooperClip in general and would suggest to merge this after review and testing and re-formatting and discuss the further refactoring later.

**Comment by harryhaaren** [comment]
@coderkun @sub26nico, if you have time to test, checking this PR would be really helpful - I'll test too before merge of course, but I'd really prefer not break stuff... so more eyes is better!

**Comment by sub26nico** [comment]
@harryhaaren , I try to test it this week.

**Comment by sub26nico** [comment]
I have tested this PR :
- Record and launch loops
- sends and returs tracks
- save and open sessions
- Load a sample in a clip
- changing bpm while playing
- launch/stop clips with MIDI Controller
- change scenes
Everything seems to works fine.

**Comment by harryhaaren** [comment]
Thanks subnico, appreciated!

**Comment by georgkrause** [comment]
Since @sub26nico and myself tested this, I think this should be merged asap to rebase the rubberband branch. @harryhaaren I give you some time for a veto and will merge this on Thursday.

**Comment by harryhaaren** [comment]
@georgkrause go ahead and merge.

**Pull request merged**
