### PR TITLE
Full stereo processing

### PR DESCRIPTION
**Pull request by coderkun**
Implement full stereo processing for all tracks (#174) including FX (#169).

These changes are still missing to copy the data from one port to the other (R→L/L→R) if only one of them is connected—to keep a mono workflow.

@harryhaaren, please review these changes and let me know if anything should be done differently.

### CODE REVIEW

**Comment by harryhaaren** [comment]
Hi @coderkun ; impressive work, after a quick review this looks a good approach. Thanks for splitting into seperate commits / patches, greatly eases review.

What do you see as next steps regarding this?

**Comment by coderkun** [comment]
For testing it would be great if some could see if all port are working fine. I did a short session yesterday but only used the master in-/outputs, not all individual tracks, sends/returns etc.

I think the next step would be to add the special handling for mono (if only one port per track is connected). @harryhaaren, do you have any hint on how to get the connection status from Jack?

In any comment I read that you use [astyle](https://sourceforge.net/projects/astyle/) to format the code. If this is true, then to run astyle will be the final step. @harryhaaren, do you run it with any particual arguments/settings?

**Comment by nanu-c** [comment]
```
int jack_port_connected 	( 	const jack_port_t *  	port	) 	

Returns:
    number of connections to or from port.

Precondition:
    The calling client must own port. 

```
http://www.jackaudio.org/api/group__PortFunctions.html#gafa704768d67d1a30f263a9384d845b14

**Comment by coderkun** [comment]
Is there actually any special handling for mono necessary? I mean you can easily connect a mono audio source to both left and right input of luppp …

**Comment by coderkun** [comment]
@harryhaaren, I tested reading and writing of stereo files and fixed both with commit e04e2de.

If there are no bugs or required changes, the PR will be complete. Please test.

**Comment by harryhaaren** [comment]
Re specialized handling of Mono; no ideally the workflow is the exact same yes, and the mono source can be duplicated into identical L/R tracks for stereo.

Re; astyle; Yes I used it, I don't have the command easily available here - I'll have to look it up on the development machine. In short, try keep to the existing formatting - but I can fix some small indentation issues etc too - so don't worry too much. I think the value of adding stereo is much larger than a few tab/spaces issues :)

Thanks, I need to test and actually merge, I'll try get to it one evening this week. Cheers, -H

**Comment by coderkun** [comment]
Sounds good, thanks.

**Comment by harryhaaren** [comment]
Thanks, I've merged the patch of this PR!

Code was of high quality - thank you for a valuable contribution to Luppp! I've refactored bits of the indentation (your editor uses spaces, but the Luppp code has tabs), but apart from that, it went in as is!

Thanks again! -Harry

**Comment by trebmuh** [comment]
Nice work guys!
FYI: I've been incorporating it into LibraZiK.

**Pull request closed without merging**
