### PR TITLE
Fixes all leaks and adds ASAN compilation

### PR DESCRIPTION
**Pull request by napcode**
Hi,

this PR fixes all leaks I could find. There is also a PR in ntk that fixes a user-after-free that was detected when running luppp with the address sanitizer. An option to compile luppp with this has also been added.  

Regards,
Mathias

### CODE REVIEW

**Comment by harryhaaren** [comment]
Wow - nice work @napcode. I run Clang with scan-build once in a while - but these additions are the right way to do it! Reviewing..

**Comment by napcode** [comment]
Sure. Please do.

**Comment by harryhaaren** [comment]
Thanks to Johnathan for fixing https://github.com/original-male/ntk/pull/8/ quickly, solves the issue mentioned above. Still reviewing :)

**Comment by napcode** [comment]
Seems like I broke the waveforms. Also, I've found another leak. I guess I'll reopen this.

**Comment by napcode** [comment]
Hi Harry. 
Do you still consider merging this pull request or is there something missing?

**Comment by harryhaaren** [comment]
Hey! I've had little time over the last weeks - and this fell off my radar.
Thanks for the ping - I'll get to it at the weekend. Nothing remaining iirc
from testing a few weeks ago :) cheers, -Harry

**Comment by harryhaaren** [comment]
Hi @napcode - thanks for this work! Merged now, I done a rebase of the patches just now so this pull wasn't closed automatically. Thanks again! -Harry

**Comment by napcode** [comment]
Well, thanks for doing all the stuff in the first place (LAC, OpenAV etc.) :-)

**Pull request closed without merging**
