### PR TITLE
Send-Returns and per track outputs

### PR DESCRIPTION
**Pull request by geraldmwangi**
hi Harry, I've completed my work on the sends and returns per track. I've added the optional feature of per track output which just outputs the audio data that goes to the main mix.
I also added the ability to set the default status of the metronome. Setting the metronome by default to active is usefull when using luppp with nsm

### CODE REVIEW

**Comment by harryhaaren** [comment]
Thanks @geraldmwangi. Sorry for not being very responsive with regards to pull requests, I'll get to them this weekend. In future, please keep one "topic" per pull-request, makes it easier for me to keep track :smile:

Thanks for your work - will test soon, -Harry

**Comment by geraldmwangi** [comment]
Hi Harry, sorry again for pack multiple topics in one pr. I have a gig comming up on the weekend where
I need all the features listed above, so I only developed them in one branch. Thats why they come in one pr. After the gig I'll develope again in separate branches

**Comment by geraldmwangi** [comment]
Btw I've done some heavy testing under real situations (band rehearsals) of all the features. Except for the glitches on send_track_0 everything is stable

**Comment by geraldmwangi** [comment]
However the midi-mapping for the sendvol dials and FX buttons is ot yet implemented

**Comment by harryhaaren** [comment]
@geraldmwangi : reviewed this patchset just now, all seems in order. One question though, when the FX button is turned on, the Dial beside it controls the amount of audio being sent: is a default of 100% better UX than 0%? It took me a second to figure out it should be turned up.

I can fix here, and if you're OK with it, I'll push your changes + my changes then?

**Comment by harryhaaren** [comment]
@geraldmwangi , hope you don't mind my setting UX defaults and pushing - this keeps the ball rolling :) Thanks for your work - this is an awesome feature :smiley:

**Comment by geraldmwangi** [comment]
Thanks, no problem with the default 100%, although maybe 50% is better? Someone could hang a distortion on the send and blast his/her ears off :)

**Comment by harryhaaren** [comment]
Well 100% is just routing *all* audio on that track externally - to me that makes the most sense. And I'm sure there are 100 other ways users could blow up things when not knowing what they're doing... so lets focus on good UX for users who have some experience :) Thanks again for this work!

**Comment by geraldmwangi** [comment]
ok fine with that.

**Pull request closed without merging**
